DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	ID VARCHAR2(1000) PRIMARY KEY,
	PW VARCHAR2(2000) NOT NULL,
	NAME VARCHAR2(1000) NOT NULL,
	ADDR VARCHAR2(4000) NOT NULL,
	PHONE VARCHAR2(1000) NOT NULL,
	EMAIL VARCHAR2(2000) NOT NULL,
	ENABLED VARCHAR2(100) NOT NULL,
	ROLE VARCHAR2(1000) NOT NULL,
	CONSTRAINT MB_NAME_UNQ UNIQUE(NAME),
	CONSTRAINT MB_PHONE_UNQ UNIQUE(PHONE),
	CONSTRAINT MB_EMAIL_UNQ UNIQUE(EMAIL),
	CONSTRAINT MB_ENABLED_CHK CHECK (ENABLED IN('Y', 'N'))
);

INSERT INTO MEMBER VALUES('admin', '1234', '관리자', '경시도 수원시', '010-1234-5678', 'kh@naver.com', 'Y', 'ADMIN');

SELECT * FROM MEMBER;